// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.lovecws.mumu.protobuf.news;

public final class News {
  private News() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnews.proto\022\036com.lovecws.mumu.protobuf." +
      "news\"\351\001\n\017SinaFinanceNews\022\016\n\006htitle\030\001 \001(\t" +
      "\022\020\n\010keywords\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022" +
      "\013\n\003url\030\004 \001(\t\022\016\n\006sumary\030\005 \001(\t\022\017\n\007content\030" +
      "\006 \001(\t\022\014\n\004logo\030\007 \001(\t\022\r\n\005title\030\010 \001(\t\022\017\n\007pu" +
      "bDate\030\t \001(\t\022\021\n\tmediaName\030\n \001(\t\022\020\n\010mediaU" +
      "rl\030\013 \001(\t\022\020\n\010category\030\014 \001(\t\022\014\n\004type\030\r \001(\t" +
      "B\"\n\036com.lovecws.mumu.protobuf.newsP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_descriptor,
        new java.lang.String[] { "Htitle", "Keywords", "Description", "Url", "Sumary", "Content", "Logo", "Title", "PubDate", "MediaName", "MediaUrl", "Category", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
