// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.lovecws.mumu.protobuf.news;

/**
 * <pre>
 *用户信息
 * </pre>
 *
 * Protobuf type {@code com.lovecws.mumu.protobuf.news.SinaFinanceNews}
 */
public  final class SinaFinanceNews extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lovecws.mumu.protobuf.news.SinaFinanceNews)
    SinaFinanceNewsOrBuilder {
  // Use SinaFinanceNews.newBuilder() to construct.
  private SinaFinanceNews(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SinaFinanceNews() {
    htitle_ = "";
    keywords_ = "";
    description_ = "";
    url_ = "";
    sumary_ = "";
    content_ = "";
    logo_ = "";
    title_ = "";
    pubDate_ = "";
    mediaName_ = "";
    mediaUrl_ = "";
    category_ = "";
    type_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SinaFinanceNews(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            htitle_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            keywords_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            sumary_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            logo_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            pubDate_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            mediaName_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            mediaUrl_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            category_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lovecws.mumu.protobuf.news.News.internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lovecws.mumu.protobuf.news.News.internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lovecws.mumu.protobuf.news.SinaFinanceNews.class, com.lovecws.mumu.protobuf.news.SinaFinanceNews.Builder.class);
  }

  public static final int HTITLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object htitle_;
  /**
   * <code>string htitle = 1;</code>
   */
  public java.lang.String getHtitle() {
    java.lang.Object ref = htitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      htitle_ = s;
      return s;
    }
  }
  /**
   * <code>string htitle = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHtitleBytes() {
    java.lang.Object ref = htitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      htitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYWORDS_FIELD_NUMBER = 2;
  private volatile java.lang.Object keywords_;
  /**
   * <code>string keywords = 2;</code>
   */
  public java.lang.String getKeywords() {
    java.lang.Object ref = keywords_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keywords_ = s;
      return s;
    }
  }
  /**
   * <code>string keywords = 2;</code>
   */
  public com.google.protobuf.ByteString
      getKeywordsBytes() {
    java.lang.Object ref = keywords_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keywords_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_FIELD_NUMBER = 4;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 4;</code>
   */
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUMARY_FIELD_NUMBER = 5;
  private volatile java.lang.Object sumary_;
  /**
   * <code>string sumary = 5;</code>
   */
  public java.lang.String getSumary() {
    java.lang.Object ref = sumary_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sumary_ = s;
      return s;
    }
  }
  /**
   * <code>string sumary = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSumaryBytes() {
    java.lang.Object ref = sumary_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sumary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 6;</code>
   */
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 6;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGO_FIELD_NUMBER = 7;
  private volatile java.lang.Object logo_;
  /**
   * <code>string logo = 7;</code>
   */
  public java.lang.String getLogo() {
    java.lang.Object ref = logo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logo_ = s;
      return s;
    }
  }
  /**
   * <code>string logo = 7;</code>
   */
  public com.google.protobuf.ByteString
      getLogoBytes() {
    java.lang.Object ref = logo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 8;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 8;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBDATE_FIELD_NUMBER = 9;
  private volatile java.lang.Object pubDate_;
  /**
   * <code>string pubDate = 9;</code>
   */
  public java.lang.String getPubDate() {
    java.lang.Object ref = pubDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pubDate_ = s;
      return s;
    }
  }
  /**
   * <code>string pubDate = 9;</code>
   */
  public com.google.protobuf.ByteString
      getPubDateBytes() {
    java.lang.Object ref = pubDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pubDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIANAME_FIELD_NUMBER = 10;
  private volatile java.lang.Object mediaName_;
  /**
   * <code>string mediaName = 10;</code>
   */
  public java.lang.String getMediaName() {
    java.lang.Object ref = mediaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaName_ = s;
      return s;
    }
  }
  /**
   * <code>string mediaName = 10;</code>
   */
  public com.google.protobuf.ByteString
      getMediaNameBytes() {
    java.lang.Object ref = mediaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIAURL_FIELD_NUMBER = 11;
  private volatile java.lang.Object mediaUrl_;
  /**
   * <code>string mediaUrl = 11;</code>
   */
  public java.lang.String getMediaUrl() {
    java.lang.Object ref = mediaUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string mediaUrl = 11;</code>
   */
  public com.google.protobuf.ByteString
      getMediaUrlBytes() {
    java.lang.Object ref = mediaUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 12;
  private volatile java.lang.Object category_;
  /**
   * <code>string category = 12;</code>
   */
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <code>string category = 12;</code>
   */
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 13;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 13;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 13;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHtitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, htitle_);
    }
    if (!getKeywordsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keywords_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
    }
    if (!getSumaryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sumary_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, content_);
    }
    if (!getLogoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, logo_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, title_);
    }
    if (!getPubDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, pubDate_);
    }
    if (!getMediaNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, mediaName_);
    }
    if (!getMediaUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, mediaUrl_);
    }
    if (!getCategoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, category_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, type_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHtitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, htitle_);
    }
    if (!getKeywordsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, keywords_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
    }
    if (!getSumaryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sumary_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, content_);
    }
    if (!getLogoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, logo_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, title_);
    }
    if (!getPubDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, pubDate_);
    }
    if (!getMediaNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, mediaName_);
    }
    if (!getMediaUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, mediaUrl_);
    }
    if (!getCategoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, category_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, type_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lovecws.mumu.protobuf.news.SinaFinanceNews)) {
      return super.equals(obj);
    }
    com.lovecws.mumu.protobuf.news.SinaFinanceNews other = (com.lovecws.mumu.protobuf.news.SinaFinanceNews) obj;

    boolean result = true;
    result = result && getHtitle()
        .equals(other.getHtitle());
    result = result && getKeywords()
        .equals(other.getKeywords());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getUrl()
        .equals(other.getUrl());
    result = result && getSumary()
        .equals(other.getSumary());
    result = result && getContent()
        .equals(other.getContent());
    result = result && getLogo()
        .equals(other.getLogo());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getPubDate()
        .equals(other.getPubDate());
    result = result && getMediaName()
        .equals(other.getMediaName());
    result = result && getMediaUrl()
        .equals(other.getMediaUrl());
    result = result && getCategory()
        .equals(other.getCategory());
    result = result && getType()
        .equals(other.getType());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HTITLE_FIELD_NUMBER;
    hash = (53 * hash) + getHtitle().hashCode();
    hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
    hash = (53 * hash) + getKeywords().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + SUMARY_FIELD_NUMBER;
    hash = (53 * hash) + getSumary().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + LOGO_FIELD_NUMBER;
    hash = (53 * hash) + getLogo().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + PUBDATE_FIELD_NUMBER;
    hash = (53 * hash) + getPubDate().hashCode();
    hash = (37 * hash) + MEDIANAME_FIELD_NUMBER;
    hash = (53 * hash) + getMediaName().hashCode();
    hash = (37 * hash) + MEDIAURL_FIELD_NUMBER;
    hash = (53 * hash) + getMediaUrl().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lovecws.mumu.protobuf.news.SinaFinanceNews prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *用户信息
   * </pre>
   *
   * Protobuf type {@code com.lovecws.mumu.protobuf.news.SinaFinanceNews}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lovecws.mumu.protobuf.news.SinaFinanceNews)
      com.lovecws.mumu.protobuf.news.SinaFinanceNewsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lovecws.mumu.protobuf.news.News.internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lovecws.mumu.protobuf.news.News.internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lovecws.mumu.protobuf.news.SinaFinanceNews.class, com.lovecws.mumu.protobuf.news.SinaFinanceNews.Builder.class);
    }

    // Construct using com.lovecws.mumu.protobuf.news.SinaFinanceNews.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      htitle_ = "";

      keywords_ = "";

      description_ = "";

      url_ = "";

      sumary_ = "";

      content_ = "";

      logo_ = "";

      title_ = "";

      pubDate_ = "";

      mediaName_ = "";

      mediaUrl_ = "";

      category_ = "";

      type_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lovecws.mumu.protobuf.news.News.internal_static_com_lovecws_mumu_protobuf_news_SinaFinanceNews_descriptor;
    }

    public com.lovecws.mumu.protobuf.news.SinaFinanceNews getDefaultInstanceForType() {
      return com.lovecws.mumu.protobuf.news.SinaFinanceNews.getDefaultInstance();
    }

    public com.lovecws.mumu.protobuf.news.SinaFinanceNews build() {
      com.lovecws.mumu.protobuf.news.SinaFinanceNews result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lovecws.mumu.protobuf.news.SinaFinanceNews buildPartial() {
      com.lovecws.mumu.protobuf.news.SinaFinanceNews result = new com.lovecws.mumu.protobuf.news.SinaFinanceNews(this);
      result.htitle_ = htitle_;
      result.keywords_ = keywords_;
      result.description_ = description_;
      result.url_ = url_;
      result.sumary_ = sumary_;
      result.content_ = content_;
      result.logo_ = logo_;
      result.title_ = title_;
      result.pubDate_ = pubDate_;
      result.mediaName_ = mediaName_;
      result.mediaUrl_ = mediaUrl_;
      result.category_ = category_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lovecws.mumu.protobuf.news.SinaFinanceNews) {
        return mergeFrom((com.lovecws.mumu.protobuf.news.SinaFinanceNews)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lovecws.mumu.protobuf.news.SinaFinanceNews other) {
      if (other == com.lovecws.mumu.protobuf.news.SinaFinanceNews.getDefaultInstance()) return this;
      if (!other.getHtitle().isEmpty()) {
        htitle_ = other.htitle_;
        onChanged();
      }
      if (!other.getKeywords().isEmpty()) {
        keywords_ = other.keywords_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      if (!other.getSumary().isEmpty()) {
        sumary_ = other.sumary_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getLogo().isEmpty()) {
        logo_ = other.logo_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getPubDate().isEmpty()) {
        pubDate_ = other.pubDate_;
        onChanged();
      }
      if (!other.getMediaName().isEmpty()) {
        mediaName_ = other.mediaName_;
        onChanged();
      }
      if (!other.getMediaUrl().isEmpty()) {
        mediaUrl_ = other.mediaUrl_;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lovecws.mumu.protobuf.news.SinaFinanceNews parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lovecws.mumu.protobuf.news.SinaFinanceNews) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object htitle_ = "";
    /**
     * <code>string htitle = 1;</code>
     */
    public java.lang.String getHtitle() {
      java.lang.Object ref = htitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        htitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string htitle = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHtitleBytes() {
      java.lang.Object ref = htitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        htitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string htitle = 1;</code>
     */
    public Builder setHtitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      htitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string htitle = 1;</code>
     */
    public Builder clearHtitle() {
      
      htitle_ = getDefaultInstance().getHtitle();
      onChanged();
      return this;
    }
    /**
     * <code>string htitle = 1;</code>
     */
    public Builder setHtitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      htitle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object keywords_ = "";
    /**
     * <code>string keywords = 2;</code>
     */
    public java.lang.String getKeywords() {
      java.lang.Object ref = keywords_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keywords_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string keywords = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes() {
      java.lang.Object ref = keywords_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keywords_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string keywords = 2;</code>
     */
    public Builder setKeywords(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      keywords_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string keywords = 2;</code>
     */
    public Builder clearKeywords() {
      
      keywords_ = getDefaultInstance().getKeywords();
      onChanged();
      return this;
    }
    /**
     * <code>string keywords = 2;</code>
     */
    public Builder setKeywordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      keywords_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 4;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 4;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 4;</code>
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 4;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sumary_ = "";
    /**
     * <code>string sumary = 5;</code>
     */
    public java.lang.String getSumary() {
      java.lang.Object ref = sumary_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sumary_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sumary = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSumaryBytes() {
      java.lang.Object ref = sumary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sumary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sumary = 5;</code>
     */
    public Builder setSumary(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sumary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sumary = 5;</code>
     */
    public Builder clearSumary() {
      
      sumary_ = getDefaultInstance().getSumary();
      onChanged();
      return this;
    }
    /**
     * <code>string sumary = 5;</code>
     */
    public Builder setSumaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sumary_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 6;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 6;</code>
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 6;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 6;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object logo_ = "";
    /**
     * <code>string logo = 7;</code>
     */
    public java.lang.String getLogo() {
      java.lang.Object ref = logo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string logo = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLogoBytes() {
      java.lang.Object ref = logo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string logo = 7;</code>
     */
    public Builder setLogo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      logo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string logo = 7;</code>
     */
    public Builder clearLogo() {
      
      logo_ = getDefaultInstance().getLogo();
      onChanged();
      return this;
    }
    /**
     * <code>string logo = 7;</code>
     */
    public Builder setLogoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      logo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 8;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 8;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 8;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 8;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pubDate_ = "";
    /**
     * <code>string pubDate = 9;</code>
     */
    public java.lang.String getPubDate() {
      java.lang.Object ref = pubDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pubDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pubDate = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPubDateBytes() {
      java.lang.Object ref = pubDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pubDate = 9;</code>
     */
    public Builder setPubDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pubDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pubDate = 9;</code>
     */
    public Builder clearPubDate() {
      
      pubDate_ = getDefaultInstance().getPubDate();
      onChanged();
      return this;
    }
    /**
     * <code>string pubDate = 9;</code>
     */
    public Builder setPubDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pubDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mediaName_ = "";
    /**
     * <code>string mediaName = 10;</code>
     */
    public java.lang.String getMediaName() {
      java.lang.Object ref = mediaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mediaName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getMediaNameBytes() {
      java.lang.Object ref = mediaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mediaName = 10;</code>
     */
    public Builder setMediaName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mediaName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mediaName = 10;</code>
     */
    public Builder clearMediaName() {
      
      mediaName_ = getDefaultInstance().getMediaName();
      onChanged();
      return this;
    }
    /**
     * <code>string mediaName = 10;</code>
     */
    public Builder setMediaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mediaName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mediaUrl_ = "";
    /**
     * <code>string mediaUrl = 11;</code>
     */
    public java.lang.String getMediaUrl() {
      java.lang.Object ref = mediaUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mediaUrl = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMediaUrlBytes() {
      java.lang.Object ref = mediaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mediaUrl = 11;</code>
     */
    public Builder setMediaUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mediaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mediaUrl = 11;</code>
     */
    public Builder clearMediaUrl() {
      
      mediaUrl_ = getDefaultInstance().getMediaUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string mediaUrl = 11;</code>
     */
    public Builder setMediaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mediaUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <code>string category = 12;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string category = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string category = 12;</code>
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string category = 12;</code>
     */
    public Builder clearCategory() {
      
      category_ = getDefaultInstance().getCategory();
      onChanged();
      return this;
    }
    /**
     * <code>string category = 12;</code>
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      category_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 13;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 13;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 13;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 13;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.lovecws.mumu.protobuf.news.SinaFinanceNews)
  }

  // @@protoc_insertion_point(class_scope:com.lovecws.mumu.protobuf.news.SinaFinanceNews)
  private static final com.lovecws.mumu.protobuf.news.SinaFinanceNews DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lovecws.mumu.protobuf.news.SinaFinanceNews();
  }

  public static com.lovecws.mumu.protobuf.news.SinaFinanceNews getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SinaFinanceNews>
      PARSER = new com.google.protobuf.AbstractParser<SinaFinanceNews>() {
    public SinaFinanceNews parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SinaFinanceNews(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SinaFinanceNews> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SinaFinanceNews> getParserForType() {
    return PARSER;
  }

  public com.lovecws.mumu.protobuf.news.SinaFinanceNews getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

