// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.lovecws.mumu.protobuf.news;

public interface SinaFinanceNewsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lovecws.mumu.protobuf.news.SinaFinanceNews)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string htitle = 1;</code>
   */
  java.lang.String getHtitle();
  /**
   * <code>string htitle = 1;</code>
   */
  com.google.protobuf.ByteString
      getHtitleBytes();

  /**
   * <code>string keywords = 2;</code>
   */
  java.lang.String getKeywords();
  /**
   * <code>string keywords = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeywordsBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string url = 4;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 4;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string sumary = 5;</code>
   */
  java.lang.String getSumary();
  /**
   * <code>string sumary = 5;</code>
   */
  com.google.protobuf.ByteString
      getSumaryBytes();

  /**
   * <code>string content = 6;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 6;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string logo = 7;</code>
   */
  java.lang.String getLogo();
  /**
   * <code>string logo = 7;</code>
   */
  com.google.protobuf.ByteString
      getLogoBytes();

  /**
   * <code>string title = 8;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 8;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string pubDate = 9;</code>
   */
  java.lang.String getPubDate();
  /**
   * <code>string pubDate = 9;</code>
   */
  com.google.protobuf.ByteString
      getPubDateBytes();

  /**
   * <code>string mediaName = 10;</code>
   */
  java.lang.String getMediaName();
  /**
   * <code>string mediaName = 10;</code>
   */
  com.google.protobuf.ByteString
      getMediaNameBytes();

  /**
   * <code>string mediaUrl = 11;</code>
   */
  java.lang.String getMediaUrl();
  /**
   * <code>string mediaUrl = 11;</code>
   */
  com.google.protobuf.ByteString
      getMediaUrlBytes();

  /**
   * <code>string category = 12;</code>
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 12;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>string type = 13;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 13;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
