// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package com.lovecws.mumu.protobuf.entity;

public interface AuthRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lovecws.mumu.protobuf.entity.AuthRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();
}
