// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package com.lovecws.mumu.protobuf.entity;

public interface ChatReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lovecws.mumu.protobuf.entity.ChatReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.lovecws.mumu.protobuf.entity.ChatType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.lovecws.mumu.protobuf.entity.ChatType type = 2;</code>
   */
  com.lovecws.mumu.protobuf.entity.ChatType getType();

  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  java.lang.String getGroup();
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   *目标用户id，
   * </pre>
   *
   * <code>int32 toId = 5;</code>
   */
  int getToId();

  /**
   * <pre>
   *目标用户nick
   * </pre>
   *
   * <code>string toNick = 6;</code>
   */
  java.lang.String getToNick();
  /**
   * <pre>
   *目标用户nick
   * </pre>
   *
   * <code>string toNick = 6;</code>
   */
  com.google.protobuf.ByteString
      getToNickBytes();
}
