// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package com.lovecws.mumu.protobuf.entity;

/**
 * <pre>
 **
 * 结束直播请求
 * </pre>
 *
 * Protobuf type {@code com.lovecws.mumu.protobuf.entity.EndLiveReqBody}
 */
public  final class EndLiveReqBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lovecws.mumu.protobuf.entity.EndLiveReqBody)
    EndLiveReqBodyOrBuilder {
  // Use EndLiveReqBody.newBuilder() to construct.
  private EndLiveReqBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EndLiveReqBody() {
    time_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EndLiveReqBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lovecws.mumu.protobuf.entity.Type.internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lovecws.mumu.protobuf.entity.Type.internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lovecws.mumu.protobuf.entity.EndLiveReqBody.class, com.lovecws.mumu.protobuf.entity.EndLiveReqBody.Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lovecws.mumu.protobuf.entity.EndLiveReqBody)) {
      return super.equals(obj);
    }
    com.lovecws.mumu.protobuf.entity.EndLiveReqBody other = (com.lovecws.mumu.protobuf.entity.EndLiveReqBody) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lovecws.mumu.protobuf.entity.EndLiveReqBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 结束直播请求
   * </pre>
   *
   * Protobuf type {@code com.lovecws.mumu.protobuf.entity.EndLiveReqBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lovecws.mumu.protobuf.entity.EndLiveReqBody)
      com.lovecws.mumu.protobuf.entity.EndLiveReqBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lovecws.mumu.protobuf.entity.Type.internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lovecws.mumu.protobuf.entity.Type.internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lovecws.mumu.protobuf.entity.EndLiveReqBody.class, com.lovecws.mumu.protobuf.entity.EndLiveReqBody.Builder.class);
    }

    // Construct using com.lovecws.mumu.protobuf.entity.EndLiveReqBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lovecws.mumu.protobuf.entity.Type.internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_descriptor;
    }

    public com.lovecws.mumu.protobuf.entity.EndLiveReqBody getDefaultInstanceForType() {
      return com.lovecws.mumu.protobuf.entity.EndLiveReqBody.getDefaultInstance();
    }

    public com.lovecws.mumu.protobuf.entity.EndLiveReqBody build() {
      com.lovecws.mumu.protobuf.entity.EndLiveReqBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lovecws.mumu.protobuf.entity.EndLiveReqBody buildPartial() {
      com.lovecws.mumu.protobuf.entity.EndLiveReqBody result = new com.lovecws.mumu.protobuf.entity.EndLiveReqBody(this);
      result.time_ = time_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lovecws.mumu.protobuf.entity.EndLiveReqBody) {
        return mergeFrom((com.lovecws.mumu.protobuf.entity.EndLiveReqBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lovecws.mumu.protobuf.entity.EndLiveReqBody other) {
      if (other == com.lovecws.mumu.protobuf.entity.EndLiveReqBody.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lovecws.mumu.protobuf.entity.EndLiveReqBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lovecws.mumu.protobuf.entity.EndLiveReqBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.lovecws.mumu.protobuf.entity.EndLiveReqBody)
  }

  // @@protoc_insertion_point(class_scope:com.lovecws.mumu.protobuf.entity.EndLiveReqBody)
  private static final com.lovecws.mumu.protobuf.entity.EndLiveReqBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lovecws.mumu.protobuf.entity.EndLiveReqBody();
  }

  public static com.lovecws.mumu.protobuf.entity.EndLiveReqBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EndLiveReqBody>
      PARSER = new com.google.protobuf.AbstractParser<EndLiveReqBody>() {
    public EndLiveReqBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EndLiveReqBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EndLiveReqBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EndLiveReqBody> getParserForType() {
    return PARSER;
  }

  public com.lovecws.mumu.protobuf.entity.EndLiveReqBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

