// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package com.lovecws.mumu.protobuf.entity;

public interface JoinRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lovecws.mumu.protobuf.entity.JoinRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <code>.com.lovecws.mumu.protobuf.entity.JoinGroupResult result = 2;</code>
   */
  int getResultValue();
  /**
   * <code>.com.lovecws.mumu.protobuf.entity.JoinGroupResult result = 2;</code>
   */
  com.lovecws.mumu.protobuf.entity.JoinGroupResult getResult();

  /**
   * <code>string group = 3;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
