// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package com.lovecws.mumu.protobuf.entity;

public final class Type {
  private Type() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_AuthReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_AuthReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_AuthRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_AuthRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_JoinReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_JoinReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_JoinRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_JoinRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_ChatReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_ChatReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_ChatRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_ChatRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lovecws_mumu_protobuf_entity_EndLiveRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lovecws_mumu_protobuf_entity_EndLiveRespBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntype.proto\022 com.lovecws.mumu.protobuf." +
      "entity\"\316\001\n\013AuthReqBody\022\014\n\004time\030\001 \001(\003\022\020\n\010" +
      "deviceId\030\002 \001(\t\022\r\n\005token\030\003 \001(\t\022@\n\ndeviceT" +
      "ype\030\004 \001(\0162,.com.lovecws.mumu.protobuf.en" +
      "tity.DeviceType\022\013\n\003cid\030\005 \001(\t\022\022\n\nappVersi" +
      "on\030\006 \001(\t\022\022\n\ndeviceInfo\030\007 \001(\t\022\013\n\003seq\030\010 \001(" +
      "\003\022\014\n\004sign\030\t \001(\t\"\034\n\014AuthRespBody\022\014\n\004time\030" +
      "\001 \001(\003\"*\n\013JoinReqBody\022\014\n\004time\030\001 \001(\003\022\r\n\005gr" +
      "oup\030\002 \001(\t\"n\n\014JoinRespBody\022\014\n\004time\030\001 \001(\003\022" +
      "A\n\006result\030\002 \001(\01621.com.lovecws.mumu.proto",
      "buf.entity.JoinGroupResult\022\r\n\005group\030\003 \001(" +
      "\t\"\220\001\n\013ChatReqBody\022\014\n\004time\030\001 \001(\003\0228\n\004type\030" +
      "\002 \001(\0162*.com.lovecws.mumu.protobuf.entity" +
      ".ChatType\022\014\n\004text\030\003 \001(\t\022\r\n\005group\030\004 \001(\t\022\014" +
      "\n\004toId\030\005 \001(\005\022\016\n\006toNick\030\006 \001(\t\"\263\001\n\014ChatRes" +
      "pBody\022\014\n\004time\030\001 \001(\003\0228\n\004type\030\002 \001(\0162*.com." +
      "lovecws.mumu.protobuf.entity.ChatType\022\014\n" +
      "\004text\030\003 \001(\t\022\016\n\006fromId\030\004 \001(\005\022\020\n\010fromNick\030" +
      "\005 \001(\t\022\014\n\004toId\030\006 \001(\005\022\016\n\006toNick\030\007 \001(\t\022\r\n\005g" +
      "roup\030\010 \001(\t\"\"\n\022BeginToLiveReqBody\022\014\n\004time",
      "\030\001 \001(\003\"`\n\023BeginToLiveRespBody\022\014\n\004time\030\001 " +
      "\001(\003\022\016\n\006liveid\030\002 \001(\003\022\026\n\016rtmppublishurl\030\003 " +
      "\001(\t\022\023\n\013rtmpliveurl\030\004 \001(\t\"\036\n\016EndLiveReqBo" +
      "dy\022\014\n\004time\030\001 \001(\003\"/\n\017EndLiveRespBody\022\014\n\004t" +
      "ime\030\001 \001(\003\022\016\n\006liveid\030\002 \001(\003*f\n\nDeviceType\022" +
      "\026\n\022DEVICE_TYPE_UNKNOW\020\000\022\022\n\016DEVICE_TYPE_P" +
      "C\020\001\022\027\n\023DEVICE_TYPE_ANDROID\020\002\022\023\n\017DEVICE_T" +
      "YPE_IOS\020\003*\262\003\n\007Command\022\022\n\016COMMAND_UNKNOW\020" +
      "\000\022\031\n\025COMMAND_HANDSHAKE_REQ\020\001\022\032\n\026COMMAND_" +
      "HANDSHAKE_RESP\020\002\022\024\n\020COMMAND_AUTH_REQ\020\003\022\025",
      "\n\021COMMAND_AUTH_RESP\020\004\022\032\n\026COMMAND_JOIN_GR" +
      "OUP_REQ\020\005\022\033\n\027COMMAND_JOIN_GROUP_RESP\020\006\022\"" +
      "\n\036COMMAND_JOIN_GROUP_NOTIFY_RESP\020\007\022\024\n\020CO" +
      "MMAND_CHAT_REQ\020\010\022\025\n\021COMMAND_CHAT_RESP\020\t\022" +
      "\032\n\026COMMAND_START_SHOW_REQ\020\n\022\033\n\027COMMAND_S" +
      "TART_SHOW_RESP\020\013\022\030\n\024COMMAND_END_SHOW_REQ" +
      "\020\014\022 \n\034COMMAND_END_SHOW_NOTIFY_RESP\020\r\022\031\n\025" +
      "COMMAND_HEARTBEAT_REQ\020\016\022\025\n\021COMMAND_CLOSE" +
      "_REQ\020\017*\320\001\n\017JoinGroupResult\022\034\n\030JOIN_GROUP" +
      "_RESULT_UNKNOW\020\000\022\030\n\024JOIN_GROUP_RESULT_OK",
      "\020\001\022\037\n\033JOIN_GROUP_RESULT_NOT_EXIST\020\002\022 \n\034J" +
      "OIN_GROUP_RESULT_GROUP_FULL\020\003\022!\n\035JOIN_GR" +
      "OUP_RESULT_IN_BACKLIST\020\004\022\037\n\033JOIN_GROUP_R" +
      "ESULT_TAKEOUTED\020\005*M\n\010ChatType\022\024\n\020CHAT_TY" +
      "PE_UNKNOW\020\000\022\024\n\020CHAT_TYPE_PUBLIC\020\001\022\025\n\021CHA" +
      "T_TYPE_PRIVATE\020\002B$\n com.lovecws.mumu.pro" +
      "tobuf.entityP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lovecws_mumu_protobuf_entity_AuthReqBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lovecws_mumu_protobuf_entity_AuthReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_AuthReqBody_descriptor,
        new java.lang.String[] { "Time", "DeviceId", "Token", "DeviceType", "Cid", "AppVersion", "DeviceInfo", "Seq", "Sign", });
    internal_static_com_lovecws_mumu_protobuf_entity_AuthRespBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lovecws_mumu_protobuf_entity_AuthRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_AuthRespBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_com_lovecws_mumu_protobuf_entity_JoinReqBody_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lovecws_mumu_protobuf_entity_JoinReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_JoinReqBody_descriptor,
        new java.lang.String[] { "Time", "Group", });
    internal_static_com_lovecws_mumu_protobuf_entity_JoinRespBody_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_lovecws_mumu_protobuf_entity_JoinRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_JoinRespBody_descriptor,
        new java.lang.String[] { "Time", "Result", "Group", });
    internal_static_com_lovecws_mumu_protobuf_entity_ChatReqBody_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_lovecws_mumu_protobuf_entity_ChatReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_ChatReqBody_descriptor,
        new java.lang.String[] { "Time", "Type", "Text", "Group", "ToId", "ToNick", });
    internal_static_com_lovecws_mumu_protobuf_entity_ChatRespBody_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_lovecws_mumu_protobuf_entity_ChatRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_ChatRespBody_descriptor,
        new java.lang.String[] { "Time", "Type", "Text", "FromId", "FromNick", "ToId", "ToNick", "Group", });
    internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveReqBody_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveReqBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveRespBody_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_BeginToLiveRespBody_descriptor,
        new java.lang.String[] { "Time", "Liveid", "Rtmppublishurl", "Rtmpliveurl", });
    internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_EndLiveReqBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_com_lovecws_mumu_protobuf_entity_EndLiveRespBody_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_lovecws_mumu_protobuf_entity_EndLiveRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lovecws_mumu_protobuf_entity_EndLiveRespBody_descriptor,
        new java.lang.String[] { "Time", "Liveid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
