// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.lovecws.mumu.protobuf.user;

public interface AppUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lovecws.mumu.protobuf.user.AppUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   */
  long getUserId();

  /**
   * <code>string userName = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string userPassword = 3;</code>
   */
  java.lang.String getUserPassword();
  /**
   * <code>string userPassword = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserPasswordBytes();

  /**
   * <code>.com.lovecws.mumu.protobuf.user.SexType sexType = 4;</code>
   */
  int getSexTypeValue();
  /**
   * <code>.com.lovecws.mumu.protobuf.user.SexType sexType = 4;</code>
   */
  com.lovecws.mumu.protobuf.user.SexType getSexType();

  /**
   * <code>string userPhone = 5;</code>
   */
  java.lang.String getUserPhone();
  /**
   * <code>string userPhone = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserPhoneBytes();

  /**
   * <code>string userEmail = 6;</code>
   */
  java.lang.String getUserEmail();
  /**
   * <code>string userEmail = 6;</code>
   */
  com.google.protobuf.ByteString
      getUserEmailBytes();

  /**
   * <code>string userBirthday = 7;</code>
   */
  java.lang.String getUserBirthday();
  /**
   * <code>string userBirthday = 7;</code>
   */
  com.google.protobuf.ByteString
      getUserBirthdayBytes();

  /**
   * <code>int64 userArea = 8;</code>
   */
  long getUserArea();

  /**
   * <code>string sign = 9;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 9;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
