// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.lovecws.mumu.protobuf.user;

/**
 * <pre>
 *类型
 * </pre>
 *
 * Protobuf enum {@code com.lovecws.mumu.protobuf.user.SexType}
 */
public enum SexType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *男性
   * </pre>
   *
   * <code>MALE = 0;</code>
   */
  MALE(0),
  /**
   * <pre>
   *女性
   * </pre>
   *
   * <code>FEMALE = 1;</code>
   */
  FEMALE(1),
  /**
   * <pre>
   *未知
   * </pre>
   *
   * <code>UNKNOW = 2;</code>
   */
  UNKNOW(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *男性
   * </pre>
   *
   * <code>MALE = 0;</code>
   */
  public static final int MALE_VALUE = 0;
  /**
   * <pre>
   *女性
   * </pre>
   *
   * <code>FEMALE = 1;</code>
   */
  public static final int FEMALE_VALUE = 1;
  /**
   * <pre>
   *未知
   * </pre>
   *
   * <code>UNKNOW = 2;</code>
   */
  public static final int UNKNOW_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SexType valueOf(int value) {
    return forNumber(value);
  }

  public static SexType forNumber(int value) {
    switch (value) {
      case 0: return MALE;
      case 1: return FEMALE;
      case 2: return UNKNOW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SexType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SexType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SexType>() {
          public SexType findValueByNumber(int number) {
            return SexType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.lovecws.mumu.protobuf.user.User.getDescriptor().getEnumTypes().get(0);
  }

  private static final SexType[] VALUES = values();

  public static SexType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SexType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.lovecws.mumu.protobuf.user.SexType)
}

